- name: NGINX | Installing NGINX
    apt:
                pkg: nginx
                    state: latest
                     
- name: NGINX | Starting NGINX
    service:
                name: nginx
                    state: started
